name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - name: Run tests
        run: deno task test
      - name: Create coverage report
        run: deno task cov
      - name: Collect coverage
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./coverage.lcov
      - name: Publish package
        run: npx jsr publish
